--- #YAML:1.0
name:                Log-Report
version:             0.09
abstract:            report a problem, pluggable handlers and language support
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0.47
    Test::Pod:                     1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mark Overmeer
