--- #YAML:1.0
name:               Log-Report
version:            0.91
abstract:           report a problem, pluggable handlers and language support
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:        2.00
    Scalar::Util:  0
    Sys::Syslog:   0.27
    Test::More:    0.86
    Test::Pod:     1.00
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
