---
abstract: 'report a problem, pluggable handlers and language support'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Report
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 2.00
  Scalar::Util: 0
  Sys::Syslog: 0.27
  Test::More: 0.86
version: 0.992
