--- #YAML:1.0
name:                Log-Report
version:             0.22
abstract:            report a problem, pluggable handlers and language support
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Encode:                        2.00
    Sys::Syslog:                   0.24
    Test::More:                    0.86
    Test::Pod:                     1.00
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
